### PR TITLE
Spanish README

### PR DESCRIPTION
**Pull request by another-sapiens**
Loving the app thus far! 
Consistency is pretty hard, but I can already tell this will prove quite useful against laziness (and probably boredom).  
In the meantime, I hope you'll find this PR useful. I paraphrased a few sentences so they were more "Spanish-friendly", but now more people will be able to find this gem.  ;)
Top-notch UI, by the way.

Thank you for all your time and effort, and for your contributions to the FOSS world! 
Not only in your own app, but in FlorisBoard too.

P.S.: Any plans on making the in-app strings translatable?

### CODE REVIEW

**Comment by Glitchy-Tozier** [comment]
Hi, thank you so much for this PR, merging it!
Just yesterday I have created a small new release, so your translation should show up in the version after that!

> Consistency is pretty hard, but I can already tell this will prove quite useful against my laziness (I wanna learn how to code, you see).

Yeah, this app originally was intended just to help myself acquire  a habit, but so far I've only coded and not done any work  xD
Regarding coding: Good luck! Do you plan on working on any specific project?

> Not only in your own app, but in FlorisBoard too.

FlorisBoard :heart: 

>P.S.: Any plans on making the in-app strings translatable?

I'm not opposing it, but currently I'm too lazy to learn how all of that stuff works. Once I get 1-2 more translation-requests, I'll probably look into it.  :)

**Comment by another-sapiens** [comment]
> but so far I've only coded and not done any work xD

Never heard of such a productive procrastination!

> Regarding your coding: Good luck! Do you plan on working on any specific project?

I tried to learn Java, but for the life of me I cannot get any IDE to work properly on my PC (it's 32-bit).  So I started off with Python's basics. I'm a huge noob, but I've heard it can do some cool stuff, even if it's quite slow. Some modules like Kivy even allow you to build Android apps. Probably not ideal, but awesome nontheless. 
I don't know how I'm gonna do it, but I just want to contribute to FOSS someday (like Glitchy!).

How did you get into coding, by the way?

> Once I get 1-2 more translation-requests, I'll probably look into it, though. :)

Nice! Be sure to tell me if you do it someday, so you get the Spanish version quick.  ;)

**Comment by Glitchy-Tozier** [comment]
> I don't know how I'm gonna do it, but I just want to contribute to FOSS someday

You're already doing that ;)
Btw, in my experience it's easiest to learn programming when you have some kind of thing you want to make.

> How did you get into coding, by the way?

I learned a little some years ago, but i only picked it up last year. I discovered some fun FOSS keyboard ([8vim](https://f-droid.org/packages/inc.flide.vi8)) and decided to do something about the ... at best decent layout. Also i wanted to have a german layout. So i wrote [this](https://github.com/Glitchy-Tozier/8vim_keyboard_layout_calculator).
(I've been looking for a good FOSS keyboard for quite a while, which is why I'm really happy about FlorosBoard.)

> Nice! Be sure to tell me if you do it someday, so you get the Spanish version quick. ;)

Will do!

**Comment by another-sapiens** [comment]
> You're already doing that ;)

Fair enough. Thank you!

> So i wrote this.

I see you know Python too! And Dart, according to GitHub.  How'd you pick all that up in just a year? 

I'll take a closer look at your repo later. Real life use-cases are the most helpful when learning!
This is also what I like about FOSS. One can learn so much by just looking at others' code. 

> I'm really happy about FlorisBoard

Same here. All the effort that was put into it has made it THE best FOSS board imho. 
Again, thank you for all your contributions!

**Comment by Glitchy-Tozier** [comment]
> How'd you pick all that up in just a year?

You don't believe this thing when you start out, but learning a new programming language isn't that difficult when you already have experience in another one.

The things i can think of that are most difficult when programming are
1. Naming variables well. (Insanely difficult but important)
2. Learning to translate your thoughts into code. ("I want to print numbers 1 to 100 in the console. And i want to skip Number 75. How do i do this?)
3. Learning programming concepts like 
  - types (string, int, etc),
  - `if/else`,
  - `for`-loops, 
  - functions, 
  - object-oriented programming,
  - and so much more.

None of those things get lost between languages. You only need to learn smaller things like syntax; your main skills stay with you, though.

Python is fun, and i think it's a great (and not too frustrating) first language!

>This is also what I like about FOSS. One can learn so much by just looking at others' code.

Yup, for example it was really handy that i could learn from (copy) some parts of FlorisBoard's file structure for F-Droid.

Fun fact: `@ patrickgold` actually helped me test this app before release!  :)

**Comment by Glitchy-Tozier** [comment]
> How'd you pick all that up in just a year?

Also, I neglected university a little too much. Turns out programming is the ultimate tool for procrastination, once you're having fun with a project. 😅

**Comment by another-sapiens** [comment]
> Naming variables well

You mean naming them in a clear, readable way?

> programming concepts

After some time of learning, I think I got most of the core concepts you mentioned. The hardest thing for me is learning the "vocabulary", like actually using modules, libraries and whatnot. How do you tackle that beast? 
Do you learn them individually, through the documentation? 

> Python is fun, and i think it's a great (and not too frustrating) first language!

Agreed! It's perfect for beginners, as even I could understand the basics rather quickly.

Out of curiosity, what language do you find yourself using more often?

> Fun fact: @ patrickgold actually helped me test this app before release! :)

Pat's amazing. Like, how does he manage to have time for everything? 
Both of you are extremely active, actually. What's your secret? Tell me it's coffee!

**Comment by another-sapiens** [comment]
> Turns out programming is the ultimate tool for procrastination

Oof! Now I now what awaits me.  Even worse, I'm hyped!

**Comment by Glitchy-Tozier** [comment]
> You mean naming them in a clear, readable way?

Exactly. It's really nice when you find a better name for something and your script makes way more sense, all of the sudden. Makes it easier to think.

> How do you tackle that beast?

Not sure whether that answers your question, but i mainly look up how to do something ("Flutter how to style a button") and remember the things i often use.

>Out of curiosity, what language do you find yourself using more often?

I don't quite understand the question, but I enjoy every language I learned. Currently I only use Dart (via Flutter), and solely for the purpose of this app, Githo.

Did that help you in any way?

> Both of you are extremely active, actually. What's your secret? Tell me it's coffee!

I don't drink coffee. Like at all. 🙃 Not a fan of depending on something to keep me awake.

Why I get (so much?) coding done: Probably 
1. because it's fun,
2. again, as a means to avoid doing more difficult things
3. I also can get really hyped about projects.  :)

How I'm so active on GitHub: I think it's because i don't have social media other than chat-apps (like Signal). So GitHub might actually be a social-media-replacement for me. 🤔

**Comment by another-sapiens** [comment]
> i mainly look up how to do something ("Flutter how to style a button") and remember the things i often use.

Ohh, so, for example, you learn the basics through a tutorial, and then learn more specific parts by looking them up? 

> Did that help you in any way?

Yep. So, the language usefulness depends on the task, right? 

> again, as a means to avoid doing more difficult things

Harder than coding? I'm spooked. 

> I also can get really hyped about projects. :)

FlorisBoard!

> I think it's because i don't have social media other than chat-apps

Same here!  I think our reasons behind that and our enthusiasm for Floris are probably one and the same.  ;)

**Comment by Glitchy-Tozier** [comment]
> Ohh, so, for example, you learn the basics through a tutorial, and then learn more specific parts by looking them up?

Exactly! For Flutter I watched a ~5h tutorial (the longest Video i have ever watched, I think) over the course of a few days, then I started working on this app.

> Yep. So, the language usefulness depends on the task, right?

Absolutely!

> Harder than coding? I'm spooked.

Well, harder in the sense that actually sitting down to do it requires overcoming laziness. Exercising, practising things, studying, stuff like that.

> Same here! I think our reasons behind that and our enthusiasm for Floris are probably one and the same. ;)

Also, it's really nice to finally have a keyboard that
1. doesn't connect to the internet
2. is usable
3. is working on important features
4. is active.

Additionally, I really liked how warmly feature requests (and bug reports) were greeted!

**Comment by another-sapiens** [comment]
> Exactly! For Flutter I watched a ~5h tutorial

Ah, I did that for Python and it made the difference. At least for the core concepts.

> harder in the sense that actually sitting down to do it requires overcoming laziness.

You're right. It's harder to put effort into things we're not (too) hyped for. Passion brings the best of us.

> Additionally, I really liked how warmly feature requests (and bug reports) were greeted!

Same! Even trivial requests weren't ignored, and imo it's those little things that make it shine. 
Also, each update really improves the experience. We don't just get an obscure "bugs fixed" in the changelog. I'm absolutely hyped every time I see a new version filled with new features I wouldn't expect a FOSSboard to have, like glide typing (which has improved tremendously, and i'm using right now). It's THE best one, and it just keeps getting better.

Okay, enough fanboying for today. :p

**Comment by Glitchy-Tozier** [comment]
> You're right. It's harder to put effort into things we're not (too) hyped for. Passion brings the best of us.

Very poetic!  ;)

> FlorisBoard and fun things

In general I absolutely love changelogs. It's really weird!  xD

Btw, you can message me on Element, if you need anything (and if you use it). This way we don't have to spam GitHub with off-topic comments. :)
`@maple-glitchy:matrix.org`

**Comment by another-sapiens** [comment]
> @maple-glitchy:matrix.org

@another-sapiens:matrix.org should've just messaged you. ;)

**Comment by Glitchy-Tozier** [comment]
@another-sapiens Could you check whether the Spanish description still is in-line with the English one?

The main change I made was turning "steps" into "levels" to show that they shouldn't be unrelated steps. Instead, they should be something like "levels of potency" of the final habit.

**Comment by another-sapiens** [comment]
@Glitchy-Tozier Done!

**Pull request merged**
